# Generated by Django 3.1.5 on 2021-01-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litBlog', '0004_auto_20210122_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
