# Generated by Django 3.1.5 on 2021-01-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litBlog', '0014_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
