# Generated by Django 3.1.5 on 2021-01-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litBlog', '0015_auto_20210124_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
    ]
